import { cookies } from "next/headers";
import { SessionProvider } from "next-auth/react";

import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/react";

import { Providers } from "./_components/providers";

import "@/styles/globals.css";

export const metadata = {
	title: {
		template: "%s | ThreadIt",
		default: "ThreadIt",
	},
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

type Props = {
	children: React.ReactNode;
};

const Layout = ({ children }: Props) => {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<Providers>
					<TRPCReactProvider cookies={cookies().toString()}>
						<SessionProvider>{children}</SessionProvider>
						<Toaster position="bottom-right" closeButton />
					</TRPCReactProvider>
				</Providers>
			</body>
		</html>
	);
};

export default Layout;
